name: Build and release docker image

on:
    workflow_dispatch:
        inputs:
            tag:
                description: 'Tag of sshpiper to use as a base'
                required: true
                type: string

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Clone sshpiper
                run: |
                    git clone https://github.com/tg123/sshpiper.git
                    cd sshpiper
                    git checkout "${{ github.event.inputs.tag }}"
                    git submodule update --init --recursive
                    cp -r ../build/* ./
                    go get github.com/fatih/color

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v3

            -   name: 'Login to GitHub Container Registry'
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{github.actor}}
                    password: ${{secrets.GITHUB_TOKEN}}

            -   name: Extract metadata (tags, labels) for Docker
                id: meta
                uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
                with:
                    images: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
                    tags: |
                        ${{ github.event.inputs.tag }}

            -   name: Build and push
                uses: docker/build-push-action@v4
                with:
                    context: sshpiper
                    platforms: linux/amd64,linux/arm64
                    build-args: |
                        BUILDTAGS=full
                    push: true
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
